Automatic release notes Add automatic release notes generation based on GH releases

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -33,6 +33,38 @@ jobs:
     # Install the .NET SDK indicated in the global.json file
     - name: Setup .NET
       uses: actions/setup-dotnet@v3
+         
+
+    - name: Update release notes
+      if: github.event_name == 'release' 
+      env:
+        RELEASE_NAME: ${{ github.event.release.name }}
+        RELEASE_BODY: ${{ github.event.release.body }}
+      run: |   
+        $name = $env:RELEASE_NAME
+        $body = $env:RELEASE_BODY
+        if($body -or $name){
+            $releaseNotes = "# Release ${{ github.event.release.tag_name }}" 
+            if($name){
+                $releaseNotes = $releaseNotes + " - "  + $name
+            }
+            if($body){
+                $releaseNotes = $releaseNotes + "`r`n`r`n"  + $body
+            }
+            
+            foreach($csProjFileName in (Get-ChildItem "${{ github.workspace }}" -Recurse -Include *.csproj)) {
+                Write-Host "Found project file '$csProjFileName'"
+                $csProjDoc = [xml](Get-Content $csProjFileName)
+                $releaseNotesNode = $csProjDoc.SelectSingleNode("Project/PropertyGroup/PackageReleaseNotes")
+
+                if($releaseNotesNode.InnerText -clike "RELEASE_NOTES_PLACEHOLDER*") 
+                {
+                    Write-Host "`tPATCHING '$csProjFileName' with new release notes"
+                    $releaseNotesNode.InnerText = "$releaseNotes"
+                    $csProjDoc.Save($csProjFileName)
+                }
+            }
+        }    
 
     # Create the NuGet package in the folder from the environment variable NuGetDirectory
     - run: dotnet pack --configuration Release --output ${{ env.NuGetDirectory }}
@@ -54,6 +86,7 @@ jobs:
       run: dotnet test --configuration Release --logger "trx;LogFileName=test-results.trx"
     - name: Upload test results
       uses: actions/upload-artifact@v3
+      if: success() || failure()    # run this step even if previous step failed
       with:
         name: TestResult
         if-no-files-found: error
@@ -82,4 +115,3 @@ jobs:
           foreach($file in (Get-ChildItem "${{ env.NuGetDirectory }}" -Recurse -Include *.nupkg)) {
               dotnet nuget push $file --api-key "$key" --source "$source" --skip-duplicate
           } 
-  
